// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.906
package inputs

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

type PasswordReq struct {
	minLength          int
	uppercase          bool
	lowercase          bool
	digit              bool
	specialChar        bool
	specialCharPattern string
}

const specialCharPattern = `[!@#$%^&*()_+\-=<>;:?\/\[\]{}\\|~]`

func defaultPasswordReq() PasswordReq {
	return PasswordReq{
		minLength:          8,
		uppercase:          true,
		lowercase:          true,
		digit:              true,
		specialChar:        true,
		specialCharPattern: specialCharPattern,
	}
}

func NewPasswordRequirements() PasswordReq {
	return PasswordReq{}
}

var _ = templruntime.GeneratedTemplate
