package inputs

var States = []option{
	{Label: "Alabama", Value: "AL"},
	{Label: "Alaska", Value: "AK"},
	{Label: "Arizona", Value: "AZ"},
	{Label: "Arkansas", Value: "AR"},
	{Label: "California", Value: "CA"},
	{Label: "Colorado", Value: "CO"},
	{Label: "Connecticut", Value: "CT"},
	{Label: "Delaware", Value: "DE"},
	{Label: "Florida", Value: "FL"},
	{Label: "Georgia", Value: "GA"},
	{Label: "Hawaii", Value: "HI"},
	{Label: "Idaho", Value: "ID"},
	{Label: "Illinois", Value: "IL"},
	{Label: "Indiana", Value: "IN"},
	{Label: "Iowa", Value: "IA"},
	{Label: "Kansas", Value: "KS"},
	{Label: "Kentucky", Value: "KY"},
	{Label: "Louisiana", Value: "LA"},
	{Label: "Maine", Value: "ME"},
	{Label: "Maryland", Value: "MD"},
	{Label: "Massachusetts", Value: "MA"},
	{Label: "Michigan", Value: "MI"},
	{Label: "Minnesota", Value: "MN"},
	{Label: "Mississippi", Value: "MS"},
	{Label: "Missouri", Value: "MO"},
	{Label: "Montana", Value: "MT"},
	{Label: "Nebraska", Value: "NE"},
	{Label: "Nevada", Value: "NV"},
	{Label: "New Hampshire", Value: "NH"},
	{Label: "New Jersey", Value: "NJ"},
	{Label: "New Mexico", Value: "NM"},
	{Label: "New York", Value: "NY"},
	{Label: "North Carolina", Value: "NC"},
	{Label: "North Dakota", Value: "ND"},
	{Label: "Ohio", Value: "OH"},
	{Label: "Oklahoma", Value: "OK"},
	{Label: "Oregon", Value: "OR"},
	{Label: "Pennsylvania", Value: "PA"},
	{Label: "Rhode Island", Value: "RI"},
	{Label: "South Carolina", Value: "SC"},
	{Label: "South Dakota", Value: "SD"},
	{Label: "Tennessee", Value: "TN"},
	{Label: "Texas", Value: "TX"},
	{Label: "Utah", Value: "UT"},
	{Label: "Vermont", Value: "VT"},
	{Label: "Virginia", Value: "VA"},
	{Label: "Washington", Value: "WA"},
	{Label: "West Virginia", Value: "WV"},
	{Label: "Wisconsin", Value: "WI"},
	{Label: "Wyoming", Value: "WY"},
}

var Countries = []option{
	{Label: "Afghanistan", Value: "AF"},
	{Label: "Albania", Value: "AL"},
	{Label: "Algeria", Value: "DZ"},
	{Label: "Andorra", Value: "AD"},
	{Label: "Angola", Value: "AO"},
	{Label: "Antigua and Barbuda", Value: "AG"},
	{Label: "Argentina", Value: "AR"},
	{Label: "Armenia", Value: "AM"},
	{Label: "Australia", Value: "AU"},
	{Label: "Austria", Value: "AT"},
	{Label: "Azerbaijan", Value: "AZ"},
	{Label: "Bahamas", Value: "BS"},
	{Label: "Bahrain", Value: "BH"},
	{Label: "Bangladesh", Value: "BD"},
	{Label: "Barbados", Value: "BB"},
	{Label: "Belarus", Value: "BY"},
	{Label: "Belgium", Value: "BE"},
	{Label: "Belize", Value: "BZ"},
	{Label: "Benin", Value: "BJ"},
	{Label: "Bhutan", Value: "BT"},
	{Label: "Bolivia", Value: "BO"},
	{Label: "Bosnia and Herzegovina", Value: "BA"},
	{Label: "Botswana", Value: "BW"},
	{Label: "Brazil", Value: "BR"},
	{Label: "Brunei Darussalam", Value: "BN"},
	{Label: "Bulgaria", Value: "BG"},
	{Label: "Burkina Faso", Value: "BF"},
	{Label: "Burundi", Value: "BI"},
	{Label: "Cabo Verde", Value: "CV"},
	{Label: "Cambodia", Value: "KH"},
	{Label: "Cameroon", Value: "CM"},
	{Label: "Canada", Value: "CA"},
	{Label: "Central African Republic", Value: "CF"},
	{Label: "Chad", Value: "TD"},
	{Label: "Chile", Value: "CL"},
	{Label: "China", Value: "CN"},
	{Label: "Colombia", Value: "CO"},
	{Label: "Comoros", Value: "KM"},
	{Label: "Congo (Brazzaville)", Value: "CG"},
	{Label: "Congo (Kinshasa)", Value: "CD"},
	{Label: "Costa Rica", Value: "CR"},
	{Label: "Côte d'Ivoire", Value: "CI"},
	{Label: "Croatia", Value: "HR"},
	{Label: "Cuba", Value: "CU"},
	{Label: "Cyprus", Value: "CY"},
	{Label: "Czechia", Value: "CZ"},
	{Label: "Denmark", Value: "DK"},
	{Label: "Djibouti", Value: "DJ"},
	{Label: "Dominica", Value: "DM"},
	{Label: "Dominican Republic", Value: "DO"},
	{Label: "Ecuador", Value: "EC"},
	{Label: "Egypt", Value: "EG"},
	{Label: "El Salvador", Value: "SV"},
	{Label: "Equatorial Guinea", Value: "GQ"},
	{Label: "Eritrea", Value: "ER"},
	{Label: "Estonia", Value: "EE"},
	{Label: "Eswatini", Value: "SZ"},
	{Label: "Ethiopia", Value: "ET"},
	{Label: "Fiji", Value: "FJ"},
	{Label: "Finland", Value: "FI"},
	{Label: "France", Value: "FR"},
	{Label: "Gabon", Value: "GA"},
	{Label: "Gambia", Value: "GM"},
	{Label: "Georgia", Value: "GE"},
	{Label: "Germany", Value: "DE"},
	{Label: "Ghana", Value: "GH"},
	{Label: "Greece", Value: "GR"},
	{Label: "Grenada", Value: "GD"},
	{Label: "Guatemala", Value: "GT"},
	{Label: "Guinea", Value: "GN"},
	{Label: "Guinea-Bissau", Value: "GW"},
	{Label: "Guyana", Value: "GY"},
	{Label: "Haiti", Value: "HT"},
	{Label: "Honduras", Value: "HN"},
	{Label: "Hungary", Value: "HU"},
	{Label: "Iceland", Value: "IS"},
	{Label: "India", Value: "IN"},
	{Label: "Indonesia", Value: "ID"},
	{Label: "Iran", Value: "IR"},
	{Label: "Iraq", Value: "IQ"},
	{Label: "Ireland", Value: "IE"},
	{Label: "Israel", Value: "IL"},
	{Label: "Italy", Value: "IT"},
	{Label: "Jamaica", Value: "JM"},
	{Label: "Japan", Value: "JP"},
	{Label: "Jordan", Value: "JO"},
	{Label: "Kazakhstan", Value: "KZ"},
	{Label: "Kenya", Value: "KE"},
	{Label: "Kiribati", Value: "KI"},
	{Label: "North Korea", Value: "KP"},
	{Label: "South Korea", Value: "KR"},
	{Label: "Kuwait", Value: "KW"},
	{Label: "Kyrgyzstan", Value: "KG"},
	{Label: "Lao People's Democratic Republic", Value: "LA"},
	{Label: "Latvia", Value: "LV"},
	{Label: "Lebanon", Value: "LB"},
	{Label: "Lesotho", Value: "LS"},
	{Label: "Liberia", Value: "LR"},
	{Label: "Libya", Value: "LY"},
	{Label: "Liechtenstein", Value: "LI"},
	{Label: "Lithuania", Value: "LT"},
	{Label: "Luxembourg", Value: "LU"},
	{Label: "Madagascar", Value: "MG"},
	{Label: "Malawi", Value: "MW"},
	{Label: "Malaysia", Value: "MY"},
	{Label: "Maldives", Value: "MV"},
	{Label: "Mali", Value: "ML"},
	{Label: "Malta", Value: "MT"},
	{Label: "Marshall Islands", Value: "MH"},
	{Label: "Mauritania", Value: "MR"},
	{Label: "Mauritius", Value: "MU"},
	{Label: "Mexico", Value: "MX"},
	{Label: "Micronesia (Federated States of)", Value: "FM"},
	{Label: "Moldova", Value: "MD"},
	{Label: "Monaco", Value: "MC"},
	{Label: "Mongolia", Value: "MN"},
	{Label: "Montenegro", Value: "ME"},
	{Label: "Morocco", Value: "MA"},
	{Label: "Mozambique", Value: "MZ"},
	{Label: "Myanmar", Value: "MM"},
	{Label: "Namibia", Value: "NA"},
	{Label: "Nauru", Value: "NR"},
	{Label: "Nepal", Value: "NP"},
	{Label: "Netherlands", Value: "NL"},
	{Label: "New Zealand", Value: "NZ"},
	{Label: "Nicaragua", Value: "NI"},
	{Label: "Niger", Value: "NE"},
	{Label: "Nigeria", Value: "NG"},
	{Label: "North Macedonia", Value: "MK"},
	{Label: "Norway", Value: "NO"},
	{Label: "Oman", Value: "OM"},
	{Label: "Pakistan", Value: "PK"},
	{Label: "Palau", Value: "PW"},
	{Label: "Palestine, State of", Value: "PS"},
	{Label: "Panama", Value: "PA"},
	{Label: "Papua New Guinea", Value: "PG"},
	{Label: "Paraguay", Value: "PY"},
	{Label: "Peru", Value: "PE"},
	{Label: "Philippines", Value: "PH"},
	{Label: "Poland", Value: "PL"},
	{Label: "Portugal", Value: "PT"},
	{Label: "Qatar", Value: "QA"},
	{Label: "Romania", Value: "RO"},
	{Label: "Russian Federation", Value: "RU"},
	{Label: "Rwanda", Value: "RW"},
	{Label: "Saint Kitts and Nevis", Value: "KN"},
	{Label: "Saint Lucia", Value: "LC"},
	{Label: "Saint Vincent and the Grenadines", Value: "VC"},
	{Label: "Samoa", Value: "WS"},
	{Label: "San Marino", Value: "SM"},
	{Label: "Sao Tome and Principe", Value: "ST"},
	{Label: "Saudi Arabia", Value: "SA"},
	{Label: "Senegal", Value: "SN"},
	{Label: "Serbia", Value: "RS"},
	{Label: "Seychelles", Value: "SC"},
	{Label: "Sierra Leone", Value: "SL"},
	{Label: "Singapore", Value: "SG"},
	{Label: "Slovakia", Value: "SK"},
	{Label: "Slovenia", Value: "SI"},
	{Label: "Solomon Islands", Value: "SB"},
	{Label: "Somalia", Value: "SO"},
	{Label: "South Africa", Value: "ZA"},
	{Label: "South Sudan", Value: "SS"},
	{Label: "Spain", Value: "ES"},
	{Label: "Sri Lanka", Value: "LK"},
	{Label: "Sudan", Value: "SD"},
	{Label: "Suriname", Value: "SR"},
	{Label: "Sweden", Value: "SE"},
	{Label: "Switzerland", Value: "CH"},
	{Label: "Syrian Arab Republic", Value: "SY"},
	{Label: "Taiwan", Value: "TW"},
	{Label: "Tajikistan", Value: "TJ"},
	{Label: "Tanzania, United Republic of", Value: "TZ"},
	{Label: "Thailand", Value: "TH"},
	{Label: "Timor-Leste", Value: "TL"},
	{Label: "Togo", Value: "TG"},
	{Label: "Tonga", Value: "TO"},
	{Label: "Trinidad and Tobago", Value: "TT"},
	{Label: "Tunisia", Value: "TN"},
	{Label: "Türkiye", Value: "TR"}, // Formerly Turkey
	{Label: "Turkmenistan", Value: "TM"},
	{Label: "Tuvalu", Value: "TV"},
	{Label: "Uganda", Value: "UG"},
	{Label: "Ukraine", Value: "UA"},
	{Label: "United Arab Emirates", Value: "AE"},
	{Label: "United Kingdom", Value: "GB"},
	{Label: "United States of America", Value: "US"},
	{Label: "Uruguay", Value: "UY"},
	{Label: "Uzbekistan", Value: "UZ"},
	{Label: "Vanuatu", Value: "VU"},
	{Label: "Venezuela", Value: "VE"},
	{Label: "Viet Nam", Value: "VN"},
	{Label: "Yemen", Value: "YE"},
	{Label: "Zambia", Value: "ZM"},
	{Label: "Zimbabwe", Value: "ZW"},
}
