// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.924
package styles

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func FS_XS() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`font-size:clamp(0.75rem, 0.6818rem + 0.2424vw, 0.9rem);`)
	templ_7745c5c3_CSSID := templ.CSSID(`FS_XS`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func FS_SM() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`font-size:clamp(0.8333rem, 0.7576rem + 0.303vw, 1rem);`)
	templ_7745c5c3_CSSID := templ.CSSID(`FS_SM`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func FS_MD() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`font-size:clamp(1rem, 0.9091rem + 0.3636vw, 1.2rem);`)
	templ_7745c5c3_CSSID := templ.CSSID(`FS_MD`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func FS_LG() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`font-size:clamp(1.2rem, 1.0909rem + 0.4848vw, 1.44rem);`)
	templ_7745c5c3_CSSID := templ.CSSID(`FS_LG`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func FS_XL() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`font-size:clamp(1.44rem, 1.3091rem + 0.606vw, 1.728rem);   
}

css FS_2XL() {
    font-size: clamp(1.728rem, 1.5709rem + 0.7272vw, 2.074rem);   
}

css FS_3XL() {
    font-size: clamp(2.074rem, 1.8818rem + 0.909vw, 2.488rem);  
}

css FS_4XL() {
    font-size: clamp(2.488rem, 2.2424rem + 1.0908vw, 2.986rem);   
}

css FS_5XL() {
    font-size: clamp(2.986rem, 2.6818rem + 1.3332vw, 3.583rem);   
}

css FS_Custom(value string) {
    font-size: { value };`)
	templ_7745c5c3_CSSID := templ.CSSID(`FS_XL`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

func FW_Bold() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`font-weight:bold;`)
	templ_7745c5c3_CSSID := templ.CSSID(`FW_Bold`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

var _ = templruntime.GeneratedTemplate
